# Generated by Django 3.1.3 on 2020-12-10 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('EMPLOYE_AGENCE', 'EMPLOYE_AGENCE'), ('RESPONSABLE_AGENCE', 'RESPONSABLE_AGENCE'), ('AGENT_COMPENSATION', 'AGENT_COMPENSATION')], max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
                ('nni', models.CharField(blank=True, max_length=50, null=True)),
                ('piece', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montat', models.FloatField(default=0.0)),
                ('motif', models.TextField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_WITHDRAWED', 'NOT_WITHDRAWED'), ('TO_VALIDATE', 'TO_VALIDATE'), ('WITHDRAWED', 'WITHDRAWED'), ('CANCELED', 'CANCELED')], max_length=50)),
                ('is_edited', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modifcation', models.DateTimeField(auto_now=True, null=True)),
                ('user_created', models.IntegerField(null=True)),
                ('user_edited', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'transaction_model',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'agent',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('01', 'INF_3000'), ('02', 'SUP_3000'), ('03', 'RETRAIT'), ('04', 'COMP_VERSEMENT'), ('05', 'COMP_RETRAIT')], max_length=4)),
                ('date', models.DateTimeField()),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.agence')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transactionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Cloture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('solde', models.FloatField(default=0.0)),
                ('frais', models.FloatField(default=0.0)),
                ('dette', models.FloatField(default=0.0)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures', to='api.agence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cloture',
            },
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('transactionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.transactionmodel')),
                ('expediteur', models.IntegerField(null=True)),
                ('frais_origine', models.FloatField(default=0.0)),
                ('frais_destination', models.FloatField(default=0.0)),
                ('frais_societe', models.FloatField(default=0.0)),
                ('type_transaction', models.CharField(choices=[('01', 'INF_3000'), ('02', 'SUP_3000')], max_length=4)),
                ('agence_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='api.agence')),
                ('agence_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='api.agence')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_recus', to='users.client')),
            ],
            options={
                'db_table': 'transfert',
            },
            bases=('users.transactionmodel',),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('agence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='api.agence')),
            ],
            options={
                'db_table': 'responsable',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='api.agence')),
            ],
            options={
                'db_table': 'employee',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('transactionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.transactionmodel')),
                ('type_transaction', models.CharField(choices=[('04', 'COMP_VERSEMENT'), ('05', 'COMP_RETRAIT')], max_length=4)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='api.agence')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='users.agent')),
            ],
            options={
                'db_table': 'compensation',
            },
            bases=('users.transactionmodel',),
        ),
    ]
