# Generated by Django 3.1.3 on 2020-12-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201212_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='type_transaction',
            field=models.CharField(choices=[('01', 'INF_3000'), ('02', 'SUP_3000'), ('03', 'RETRAIT')], max_length=4),
        ),
    ]
