# Generated by Django 3.1.3 on 2020-12-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201212_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfert',
            name='type_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='categorie_transaction',
            field=models.CharField(choices=[('INF_3000', 'INF_3000'), ('SUP_3000', 'SUP_3000'), ('NONE', 'NONE')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfert',
            name='categorie_transaction',
            field=models.CharField(choices=[('INF_3000', 'INF_3000'), ('SUP_3000', 'SUP_3000')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compensation',
            name='type_transaction',
            field=models.CharField(choices=[('03', 'COMP_VERSEMENT'), ('04', 'COMP_RETRAIT')], max_length=4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('01', 'TRANSFERT'), ('02', 'RETRAIT'), ('03', 'COMP_VERSEMENT'), ('04', 'COMP_RETRAIT')], max_length=50),
        ),
    ]
