# Generated by Django 3.1.3 on 2020-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201216_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloture',
            name='retrait',
            field=models.FloatField(default=0.0),
        ),
    ]
