# Generated by Django 3.1.3 on 2021-02-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cloture_retrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_DigiPay',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('tel', models.CharField(blank=True, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('solde', models.FloatField(default=0.0)),
                ('client', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'client_digiPay',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('tel', models.CharField(blank=True, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('solde', models.FloatField(default=0.0)),
                ('client', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'vendor',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='type_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='agence',
        ),
        migrations.AddField(
            model_name='transfert',
            name='code_secret',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('EMPLOYE_AGENCE', 'EMPLOYE_AGENCE'), ('RESPONSABLE_AGENCE', 'RESPONSABLE_AGENCE'), ('AGENT_COMPENSATION', 'AGENT_COMPENSATION'), ('CLIENT', 'CLIENT'), ('VENDOR', 'VENDOR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='categorie_transaction',
            field=models.CharField(choices=[('INF_3000', 'INF_3000'), ('SUP_3000', 'SUP_3000'), ('NONE', 'NONE')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('01', 'TRANSFERT'), ('02', 'RETRAIT'), ('03', 'COMP_VERSEMENT'), ('04', 'COMP_RETRAIT'), ('05', 'RECHARGE'), ('06', 'PAIEMENT'), ('07', 'ENVOI'), ('08', 'REMBOURSEMENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('NOT_WITHDRAWED', 'NOT_WITHDRAWED'), ('TO_VALIDATE', 'TO_VALIDATE'), ('WITHDRAWED', 'WITHDRAWED'), ('CANCELED', 'CANCELED'), ('COMFIRMED', 'COMFIRMED')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employe',
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='model_user',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.CreateModel(
            name='Transfert_Direct',
            fields=[
                ('transactionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.transactionmodel')),
                ('code_secret', models.CharField(blank=True, default='', max_length=200)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_direct_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_direct_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfert_direct',
            },
            bases=('users.transactionmodel',),
        ),
        migrations.CreateModel(
            name='Pre_Transaction',
            fields=[
                ('transactionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.transactionmodel')),
                ('type_transaction', models.CharField(choices=[('PAIEMENT', 'PAIEMENT'), ('RETRAIT', 'RETRAIT')], max_length=30)),
                ('destinataire', models.IntegerField(null=True)),
                ('code_secret', models.CharField(blank=True, default='', max_length=200)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preTransactions_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pre_transactions',
            },
            bases=('users.transactionmodel',),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('DEMANDE_PAIEMENT', 'DEMANDE DE PAIEMENT'), ('DEMANDE_RETRAIT', 'DEMANDE DE RETRAIT'), ('RETRAIT', 'RETRAIT'), ('PAIEMENT', 'PAIEMENT'), ('ENVOI', 'ENVOI'), ('RECHARGE', 'RECHARGE')], default='DEMANDE DE PAIEMENT', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transactionmodel')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
