# Generated by Django 3.1.3 on 2021-03-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210213_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_transaction',
            name='qrcode',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='transfert',
            name='qrcode',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='transfert_direct',
            name='qrcode',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
