# Generated by Django 3.1.3 on 2021-04-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210315_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysAdmin',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sysadmin',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('DEMANDE_PAIEMENT', 'DEMANDE DE PAIEMENT'), ('DEMANDE_RETRAIT', 'DEMANDE DE RETRAIT'), ('DEMANDE_COMPENSATION', 'DEMANDE DE COMPENSATION'), ('COMPENSATION', 'COMPENSATION'), ('RETRAIT', 'RETRAIT'), ('PAIEMENT', 'PAIEMENT'), ('ENVOI', 'ENVOI'), ('RECHARGE', 'RECHARGE')], default='DEMANDE DE PAIEMENT', max_length=50),
        ),
    ]
