# Generated by Django 3.1.3 on 2021-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210417_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_transaction',
            name='libele',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='pre_transaction',
            name='livraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfert_direct',
            name='livraison',
            field=models.BooleanField(default=False),
        ),
    ]
