# Generated by Django 3.1.3 on 2021-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210417_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert_direct',
            name='delai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
