# Generated by Django 3.1.3 on 2021-04-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_transfert_direct_delai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_transaction',
            name='delai',
        ),
        migrations.RemoveField(
            model_name='transfert_direct',
            name='delai',
        ),
        migrations.AddField(
            model_name='pre_transaction',
            name='delai_livraison',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transfert_direct',
            name='delai_livraison',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='myId',
            field=models.IntegerField(null=True),
        ),
    ]
