# Generated by Django 3.1.3 on 2021-04-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210422_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='myId',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
