# Generated by Django 3.1.3 on 2021-04-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210422_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_digipay',
            name='compte_banquaire',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client_digipay',
            name='device_connecte',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client_digipay',
            name='valide_en_agence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='compte_banquaire',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
