# Generated by Django 3.1.3 on 2021-05-01 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210430_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cagnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('solde', models.FloatField(default=0.0)),
                ('objectif', models.FloatField(default=0.0)),
                ('motif', models.CharField(blank=True, max_length=200, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('verse_au_solde', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cagnote',
            },
        ),
        migrations.CreateModel(
            name='Transfert_Cagnote',
            fields=[
                ('transactionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.transactionmodel')),
                ('expediteur', models.IntegerField()),
                ('destinataire', models.IntegerField()),
            ],
            options={
                'db_table': 'transfert_cagnote',
            },
            bases=('users.transactionmodel',),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('01', 'TRANSFERT'), ('02', 'RETRAIT'), ('03', 'COMP_VERSEMENT'), ('04', 'COMP_RETRAIT'), ('05', 'RECHARGE'), ('06', 'PAIEMENT'), ('07', 'ENVOI'), ('08', 'REMBOURSEMENT'), ('09', 'DONATION'), ('10', 'RECOLTE')], max_length=50),
        ),
        migrations.CreateModel(
            name='Participants_Cagnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cagnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cagnote')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participant_cagnote',
            },
        ),
    ]
