# Generated by Django 3.1.3 on 2021-05-05 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_transfert_cagnote_type_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants_cagnote',
            name='motif',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('01', 'TRANSFERT'), ('02', 'RETRAIT'), ('03', 'COMP_VERSEMENT'), ('04', 'COMP_RETRAIT'), ('05', 'RECHARGE'), ('06', 'PAIEMENT'), ('07', 'ENVOI'), ('08', 'REMBOURSEMENT'), ('09', 'CAGNOTE'), ('10', 'RECOLTE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transfert_cagnote',
            name='type_transaction',
            field=models.CharField(choices=[('CAGNOTE', 'CAGNOTE'), ('RECOLTE', 'RECOLTE')], max_length=30),
        ),
        migrations.CreateModel(
            name='Group_Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_payement',
            },
        ),
        migrations.CreateModel(
            name='Beneficiares_GrpPayement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0.0)),
                ('motif', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grp_payement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group_payement')),
            ],
            options={
                'db_table': 'beneficiaires_group_payement',
            },
        ),
    ]
