# Generated by Django 3.1.3 on 2021-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_client_digipay_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert_direct',
            name='numero_grp_payement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('01', 'TRANSFERT'), ('02', 'RETRAIT'), ('03', 'COMP_VERSEMENT'), ('04', 'COMP_RETRAIT'), ('05', 'RECHARGE'), ('06', 'PAIEMENT'), ('07', 'ENVOI'), ('08', 'REMBOURSEMENT'), ('11', 'PAIEMENT_MASSE'), ('09', 'CAGNOTE'), ('10', 'RECOLTE')], max_length=50),
        ),
    ]
