# Generated by Django 3.1.3 on 2021-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210509_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_digipay',
            name='compte_banquaire',
        ),
        migrations.RemoveField(
            model_name='client_digipay',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='client_digipay',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='compte_banquaire',
        ),
        migrations.AddField(
            model_name='myuser',
            name='compte_banquaire',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='date_naissance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='identifiant',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
