# Generated by Django 3.1.3 on 2021-05-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210510_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_digipay',
            name='device_connecte',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='compte_banquaire',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='identifiant',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('DEMANDE_PAIEMENT', 'DEMANDE DE PAIEMENT'), ('DEMANDE_RETRAIT', 'DEMANDE DE RETRAIT'), ('DEMANDE_COMPENSATION', 'DEMANDE DE COMPENSATION'), ('COMPENSATION', 'COMPENSATION'), ('RETRAIT', 'RETRAIT'), ('PAIEMENT', 'PAIEMENT'), ('ENVOI', 'ENVOI'), ('RECHARGE', 'RECHARGE'), ('CAGNOTTE', 'CAGNOTTE')], default='DEMANDE DE PAIEMENT', max_length=50),
        ),
    ]
