# Generated by Django 3.1.3 on 2021-06-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_agent_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='cagnote',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participants_cagnote',
            name='nbre_modification',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client_digipay',
            name='client',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='client',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
