# Generated by Django 3.1.3 on 2021-06-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210601_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('01', 'TRANSFERT'), ('02', 'RETRAIT'), ('03', 'COMP_VERSEMENT'), ('04', 'COMP_RETRAIT'), ('05', 'RECHARGE'), ('06', 'PAIEMENT'), ('07', 'ENVOI'), ('08', 'REMBOURSEMENT'), ('11', 'PAIEMENT_MASSE'), ('09', 'CAGNOTE'), ('10', 'RECOLTE'), ('12', 'CAGNOTE_ANNULE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transfert_cagnote',
            name='type_transaction',
            field=models.CharField(choices=[('CAGNOTE', 'CAGNOTE'), ('RECOLTE', 'RECOLTE'), ('CAGNOTE_ANNULE', 'CAGNOTE_ANNULE')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='beneficiares_grppayement',
            table='beneficiares_GrpPayement',
        ),
        migrations.AlterModelTable(
            name='client_digipay',
            table='client_DigiPay',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='group_payement',
            table='group_Payement',
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='myUser',
        ),
        migrations.AlterModelTable(
            name='participants_cagnote',
            table='participants_Cagnote',
        ),
        migrations.AlterModelTable(
            name='pre_transaction',
            table='pre_Transaction',
        ),
        migrations.AlterModelTable(
            name='sysadmin',
            table='sysAdmin',
        ),
        migrations.AlterModelTable(
            name='transactionmodel',
            table='transactionModel',
        ),
        migrations.AlterModelTable(
            name='transfert_cagnote',
            table='transfert_Cagnote',
        ),
        migrations.AlterModelTable(
            name='transfert_direct',
            table='transfert_Direct',
        ),
    ]
