# Generated by Django 3.1.3 on 2021-06-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('token_blacklist', '0007_auto_20171017_2214'),
        ('users', '0027_auto_20210609_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficiares_GrpPayement',
            new_name='BeneficiaresGrpPayement',
        ),
        migrations.RenameModel(
            old_name='Client_DigiPay',
            new_name='ClientDigiPay',
        ),
        migrations.RenameModel(
            old_name='Group_Payement',
            new_name='GroupPayement',
        ),
        migrations.RenameModel(
            old_name='Participants_Cagnote',
            new_name='ParticipantsCagnote',
        ),
        migrations.RenameModel(
            old_name='Pre_Transaction',
            new_name='PreTransaction',
        ),
        migrations.RenameModel(
            old_name='Transfert_Cagnote',
            new_name='TransfertCagnote',
        ),
        migrations.RenameModel(
            old_name='Transfert_Direct',
            new_name='TransfertDirect',
        ),
        migrations.AlterModelTable(
            name='beneficiaresgrppayement',
            table='beneficiares_grp_payement',
        ),
        migrations.AlterModelTable(
            name='clientdigipay',
            table='client_digi_pay',
        ),
        migrations.AlterModelTable(
            name='grouppayement',
            table='group_payement',
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='my_user',
        ),
        migrations.AlterModelTable(
            name='participantscagnote',
            table='participants_cagnote',
        ),
        migrations.AlterModelTable(
            name='pretransaction',
            table='pre_transaction',
        ),
        migrations.AlterModelTable(
            name='sysadmin',
            table='sys_admin',
        ),
        migrations.AlterModelTable(
            name='transactionmodel',
            table='transaction_model',
        ),
        migrations.AlterModelTable(
            name='transfertcagnote',
            table='transfert_cagnote',
        ),
        migrations.AlterModelTable(
            name='transfertdirect',
            table='transfert_direct',
        ),
    ]
