# Generated by Django 3.1.3 on 2021-06-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210609_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('solde', models.FloatField(default=0.0)),
                ('recharge_credit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'service',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('SYSADMIN', 'SYSADMIN'), ('EMPLOYE_AGENCE', 'EMPLOYE_AGENCE'), ('RESPONSABLE_AGENCE', 'RESPONSABLE_AGENCE'), ('AGENT_COMPENSATION', 'AGENT_COMPENSATION'), ('CLIENT', 'CLIENT'), ('VENDOR', 'VENDOR'), ('SERVICE', 'SERVICE')], max_length=50),
        ),
    ]
