# Generated by Django 3.1.3 on 2021-06-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0007_auto_20171017_2214'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0029_auto_20210610_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturier',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('solde', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'facturier',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('SYSADMIN', 'SYSADMIN'), ('EMPLOYE_AGENCE', 'EMPLOYE_AGENCE'), ('RESPONSABLE_AGENCE', 'RESPONSABLE_AGENCE'), ('AGENT_COMPENSATION', 'AGENT_COMPENSATION'), ('CLIENT', 'CLIENT'), ('VENDOR', 'VENDOR'), ('FACTURIER', 'FACTURIER')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
