# Generated by Django 3.1.3 on 2021-06-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210612_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditManager',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myuser')),
                ('tel', models.CharField(blank=True, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('solde', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'credit_manager',
            },
            bases=('users.myuser', models.Model),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('SYSADMIN', 'SYSADMIN'), ('EMPLOYE_AGENCE', 'EMPLOYE_AGENCE'), ('RESPONSABLE_AGENCE', 'RESPONSABLE_AGENCE'), ('AGENT_COMPENSATION', 'AGENT_COMPENSATION'), ('CLIENT', 'CLIENT'), ('VENDOR', 'VENDOR'), ('FACTURIER', 'FACTURIER'), ('CREDIT_MANAGER', 'CREDIT_MANAGER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('01', 'TRANSFERT'), ('02', 'RETRAIT'), ('03', 'COMP_VERSEMENT'), ('04', 'COMP_RETRAIT'), ('05', 'RECHARGE'), ('06', 'PAIEMENT'), ('07', 'ENVOI'), ('08', 'REMBOURSEMENT'), ('11', 'PAIEMENT_MASSE'), ('09', 'CAGNOTE'), ('10', 'RECOLTE'), ('12', 'CAGNOTE_ANNULE'), ('13', 'PAIEMENT_FACTURE'), ('14', 'PAIEMENT_CREDIT')], max_length=50),
        ),
    ]
