# Generated by Django 3.1.3 on 2021-06-15 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210615_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigiPayServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('couleur', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'digi_pay_services',
            },
        ),
        migrations.CreateModel(
            name='ServicesInterFacturier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.digipayservices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_inter_facturier',
            },
        ),
    ]
