# Generated by Django 3.1.3 on 2021-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_digipayservices_servicesinterfacturier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesinterfacturier',
            name='service',
            field=models.CharField(choices=[('Électricité', 'Électricité'), ('Eau', 'Eau'), ('Internet', 'Internet')], max_length=50),
        ),
        migrations.DeleteModel(
            name='DigiPayServices',
        ),
    ]
