# Generated by Django 3.1.3 on 2020-12-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('commune_code', models.IntegerField(primary_key=True, serialize=False)),
                ('wilaya', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'commune',
            },
        ),
        migrations.CreateModel(
            name='TypeAgence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'type_agence',
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('solde', models.FloatField(default=0.0)),
                ('frais', models.FloatField(default=0.0)),
                ('dette', models.FloatField(default=0.0)),
                ('code_agence', models.CharField(max_length=100, unique=True)),
                ('tel', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('logitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type_agence', models.CharField(choices=[('AGENCE_INTERN', 'AGENCE_INTERN'), ('PARTNER_SILVER', 'PARTNER_SILVER'), ('PARTNER_GOLD', 'PARTNER_GOLD')], max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('last_date_cloture', models.DateTimeField(null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commune')),
            ],
            options={
                'db_table': 'agence',
            },
        ),
    ]
