# Generated by Django 3.1.3 on 2020-12-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeAgence',
        ),
    ]
