# Generated by Django 3.1.3 on 2020-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_typeagence'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='retrait',
            field=models.FloatField(default=0.0),
        ),
    ]
