# Generated by Django 3.1.3 on 2020-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agence_retrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
